### ISSUE TITLE
Can 'maximum_request_count' be harmful for interoperability?

### ISSUE THREAD

**Issue by jvirtanen** [pmembrey/molderl#54]
The recovery state contains a configurable parameter `maximum_request_count`. If this is set to a value less than 65535 (the maximum allowed by the protocol), it can cause incompatibilities with other MoldUDP64 implementations as `molderl` will silently discard request packets that have a requested message count exceeding the value.

MoldUDP64 servers, such as NASDAQ OMX Nordic and [Nassau](https://github.com/jvirtanen/nassau), cap the message count in the response packet to a value that fits within the MTU. They, however, do not impose constraints on the requested message count originating from the MoldUDP64 client.

What do you think about dropping `maximum_request_count`?

**Comment by pmembrey** [comment]
This was added as protection against poorly written clients. We have seen cases where an app has requested millions of messages and then keeps hammering the server with requests. This ultimately killed the server. Admittedly this is in part due to the way molderl persists messages.

So I'm not keen on removing it without a good alternative - although I would certainly like to be compliant with the spec :)

**Comment by jvirtanen** [comment]
Makes sense. I actually spent myself some time ironing out the kinks in the gap fill logic on the client side.

What I have planned to do about this issue is to separate the request server responding to request packets from the server sending downstream packets. I'm pretty sure NASDAQ is doing this as well. This is the architecture I have in mind:
1. There is one **server**, _n_ **request servers**, and _m_ **clients**.
2. All **request servers** and **clients** listen to downstream packets from the **server**.
3. All **request servers** are configured to recover from the **server**.
4. Each **client** is configured to recover from one of the **request servers**.

In this architecture, a badly-behaving client can swamp a request server but not the server sending downstream packets. The request server is a simple process that appears as a client to the server and a server to the clients.

This is something I have been thinking of implementing in Nassau, though I myself haven't had a need for it quite yet.

**Comment by jvirtanen** [comment]
Closing this as the initial question has been resolved.
